/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.5/samples
 */
plugins{
    application
    java
    id ("com.github.johnrengelman.shadow") version "8.1.1"
    id("org.springframework.boot") version "3.2.3" 
}

apply(plugin = "io.spring.dependency-management")

application {
    mainClass = "com.kuta.Main"
}


repositories{
    mavenCentral()
    gradlePluginPortal()
}

dependencies{
    implementation("com.google.code.gson:gson:2.10.1")
	implementation("org.springframework.boot:spring-boot-starter-thymeleaf")
	implementation("org.springframework.boot:spring-boot-starter-web")
	testImplementation("org.springframework.boot:spring-boot-starter-test")
}

tasks {
  withType<Jar> {
        manifest {
            attributes["Main-Class"] = "com.kuta.Main" 
        }

        duplicatesStrategy = DuplicatesStrategy.EXCLUDE // Exclude duplicates
        configurations["compileClasspath"].forEach { file: File ->
        from(zipTree(file.absoluteFile))
    }
    }
    shadowJar {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE // Exclude duplicates
        exclude("META-INF/LICENSE.txt") // Exclude the specific file causing conflict
        archiveBaseName.set("alfa_4")
        destinationDirectory.set(File("./"))
        mergeServiceFiles()
        manifest {
            attributes("Main-Class" to "com.kuta.Main")
        }
  }
}

// Pass default system input to gradle run (Default input stream)
tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}

tasks.named<Test>("test") {
    useJUnitPlatform()

    maxHeapSize = "1G"

    testLogging {
        events("passed")
    }
}
