/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.5/samples
 */
plugins{
    application
    java
	id("org.springframework.boot") version "3.2.3"
	id("io.spring.dependency-management") version "1.1.4"
    war
}
application {
    mainClass = "com.kuta.Main"
}
repositories{
    mavenCentral()
    gradlePluginPortal()
}
dependencies{
    implementation("com.google.code.gson:gson:2.10.1")
	implementation("org.springframework.boot:spring-boot-starter-thymeleaf")
	implementation("org.springframework.boot:spring-boot-starter-web")
	testImplementation("org.springframework.boot:spring-boot-starter-test")
}
java {
	sourceCompatibility = JavaVersion.VERSION_21
}
tasks {
  withType<Jar> {
          exclude("META-INF/LICENSE.txt") // Exclude the specific file causing conflict
        manifest {
            attributes("Main-Class" to  "com.kuta.Main")
        }

        configurations["compileClasspath"].forEach { file: File ->
        from(zipTree(file.absoluteFile))
        }
    }
    bootJar{
        //archiveBaseName.set("app")
        //destinationDirectory.set(file("./"))
    }
}

// Pass default system input to gradle run (Default input stream)
tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}

tasks.withType<Test> {
	useJUnitPlatform()
}
